

const VENDEURS = {
  v1: {
    id: 'v1',
    nom: 'Ahmed Labbeb',
    avatar: 'https://i.pravatar.cc/80?img=11',
    localisation: 'Sfax, Tunisie',
    telephone: '+216 74 000 111',
    email: 'ahmed.labbeb@agrico.tn',
    bio: 'Agriculteur avec 15 ans d\'expérience en labour de précision et travail du sol.',
    nbAvis: 124,
  },
  v2: {
    id: 'v2',
    nom: 'AgriTech Solutions',
    avatar: 'https://i.pravatar.cc/80?img=32',
    localisation: 'Tunis, Tunisie',
    telephone: '+216 71 200 300',
    email: 'contact@agritech.tn',
    bio: 'Entreprise spécialisée dans les systèmes d\'irrigation modernes et l\'agriculture durable.',
    nbAvis: 89,
  },
  v3: {
    id: 'v3',
    nom: 'Marc Leforestier',
    avatar: 'https://i.pravatar.cc/80?img=53',
    localisation: 'Nabeul, Tunisie',
    telephone: '+216 72 100 200',
    email: 'marc.leforestier@agrico.tn',
    bio: 'Expert en arboriculture et taille de vergers depuis 20 ans.',
    nbAvis: 67,
  },
  v4: {
    id: 'v4',
    nom: 'BioLab Agri',
    avatar: 'https://i.pravatar.cc/80?img=44',
    localisation: 'Sousse, Tunisie',
    telephone: '+216 73 500 600',
    email: 'biolab@agrico.tn',
    bio: 'Laboratoire d\'analyse de sols et de conseils agronomiques certifiés.',
    nbAvis: 203,
  },
  v5: {
    id: 'v5',
    nom: 'MécAgri 24/7',
    avatar: 'https://i.pravatar.cc/80?img=15',
    localisation: 'Kairouan, Tunisie',
    telephone: '+216 77 800 900',
    email: 'mecagri@agrico.tn',
    bio: 'Service de réparation et maintenance de matériel agricole disponible 24h/24.',
    nbAvis: 156,
  },
  v6: {
    id: 'v6',
    nom: 'SkyAgri',
    avatar: 'https://i.pravatar.cc/80?img=22',
    localisation: 'Monastir, Tunisie',
    telephone: '+216 73 111 222',
    email: 'skyagri@agrico.tn',
    bio: 'Spécialiste en drone agricole pour surveillance, traitement et cartographie.',
    nbAvis: 91,
  },
  v7: {
    id: 'v7',
    nom: 'BioSemence Co.',
    avatar: 'https://i.pravatar.cc/80?img=33',
    localisation: 'Béja, Tunisie',
    telephone: '+216 78 400 500',
    email: 'biosemence@agrico.tn',
    bio: 'Producteur de semences biologiques certifiées pour toutes les cultures.',
    nbAvis: 178,
  },
  v8: {
    id: 'v8',
    nom: 'FertilAgri',
    avatar: 'https://i.pravatar.cc/80?img=41',
    localisation: 'Jendouba, Tunisie',
    telephone: '+216 78 300 400',
    email: 'fertilagri@agrico.tn',
    bio: 'Fabricant d\'engrais organiques et de composts pour une agriculture saine.',
    nbAvis: 112,
  },
  v9: {
    id: 'v9',
    nom: 'EquipAgri',
    avatar: 'https://i.pravatar.cc/80?img=57',
    localisation: 'Tunis, Tunisie',
    telephone: '+216 71 900 100',
    email: 'equipagri@agrico.tn',
    bio: 'Distributeur officiel de matériel agricole neuf et reconditionné.',
    nbAvis: 245,
  },
  v10: {
    id: 'v10',
    nom: 'NutriFarm',
    avatar: 'https://i.pravatar.cc/80?img=18',
    localisation: 'Siliana, Tunisie',
    telephone: '+216 78 500 600',
    email: 'nutrifarm@agrico.tn',
    bio: 'Fournisseur d\'aliments premium pour animaux d\'élevage, certifié ISO.',
    nbAvis: 88,
  },
  v11: {
    id: 'v11',
    nom: 'WaterSmart',
    avatar: 'https://i.pravatar.cc/80?img=25',
    localisation: 'Sfax, Tunisie',
    telephone: '+216 74 200 300',
    email: 'watersmart@agrico.tn',
    bio: 'Expert en systèmes d\'arrosage intelligent et économie d\'eau agricole.',
    nbAvis: 60,
  },
  v12: {
    id: 'v12',
    nom: 'Le Jardinier Bio',
    avatar: 'https://i.pravatar.cc/80?img=37',
    localisation: 'Nabeul, Tunisie',
    telephone: '+216 72 600 700',
    email: 'jardinbio@agrico.tn',
    bio: 'Pépinière biologique spécialisée dans les plants de légumes et d\'herbes aromatiques.',
    nbAvis: 143,
  },
};

// ─── SERVICES ───────────────────────────────────────────────
const SERVICES = [
  {
    id: 's1',
    titre: 'Labour de Précision',
    categorie: 'sol',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80',
    prix: 150,
    unite: 'jour',
    rating: 4.8,
    nbAvis: 124,
    prestataire: 'v1',
    description: 'Service de labour de précision adapté à tous types de sols. Utilisation de matériel GPS dernière génération pour une précision au centimètre. Amélioration de la structure du sol, désherbage mécanique, et préparation optimale pour les semis. Intervention possible sur toute la région.',
    disponibilite: 'Disponible sous 48h',
  },
  {
    id: 's2',
    titre: 'Installation irrigation goutte-à-goutte',
    categorie: 'arrosage',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80',
    prix: 500,
    unite: 'jour',
    rating: 4.9,
    nbAvis: 89,
    prestataire: 'v2',
    description: 'Installation complète de systèmes d\'irrigation goutte-à-goutte pour toutes cultures. Étude préalable du terrain, dimensionnement hydraulique, pose des tuyaux et goutteurs, mise en service et formation. Économie d\'eau garantie jusqu\'à 40% par rapport à l\'aspersion.',
    disponibilite: 'Sur rendez-vous',
  },
  {
    id: 's3',
    titre: 'Taille de vergers',
    categorie: 'plantes',
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80',
    prix: 90,
    unite: 'jour',
    rating: 4.7,
    nbAvis: 67,
    prestataire: 'v3',
    description: 'Taille professionnelle de vergers d\'oliviers, d\'agrumes, de pommiers et poiriers. Taille de formation pour les jeunes arbres, taille de fructification pour les arbres adultes, et taille de rajeunissement. Tous les déchets évacués inclus dans la prestation.',
    disponibilite: 'Disponible de novembre à mars',
  },
  {
    id: 's4',
    titre: 'Analyse de sol complète',
    categorie: 'sol',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80',
    prix: 85,
    unite: 'analyse',
    rating: 4.6,
    nbAvis: 203,
    prestataire: 'v4',
    description: 'Analyse complète de vos sols comprenant : pH, taux de matière organique, azote, phosphore, potassium, oligo-éléments, texture et structure. Rapport détaillé avec recommandations agronomiques personnalisées. Résultats disponibles sous 5 jours ouvrables.',
    disponibilite: 'Disponible immédiatement',
  },
  {
    id: 's5',
    titre: 'Réparation tracteur à domicile',
    categorie: 'materiels',
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&q=80',
    prix: 65,
    unite: 'heure',
    rating: 4.9,
    nbAvis: 156,
    prestataire: 'v5',
    description: 'Réparation et entretien de tracteurs et matériel agricole directement sur votre exploitation. Diagnostic électronique, remplacement de pièces, révision moteur, hydraulique et transmission. Intervention d\'urgence possible 24h/24, 7j/7. Pièces d\'origine garanties.',
    disponibilite: 'Disponible 24h/24',
  },
  {
    id: 's6',
    titre: 'Drone de surveillance cultures',
    categorie: 'materiels',
    image: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&q=80',
    prix: 250,
    unite: 'jour',
    rating: 4.8,
    nbAvis: 91,
    prestataire: 'v6',
    description: 'Surveillance aérienne de vos cultures par drone équipé de capteurs multispectraux. Détection précoce des maladies, stress hydrique et carences. Cartographie NDVI, comptage de plants, estimation de rendement. Rapport d\'analyse fourni sous 24h après vol.',
    disponibilite: 'Selon météo, réservation conseillée',
  },
  {
    id: 's7',
    titre: 'Plantation d\'oliviers',
    categorie: 'plantation',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
    prix: 120,
    unite: 'jour',
    rating: 4.5,
    nbAvis: 45,
    prestataire: 'v3',
    description: 'Service de plantation professionnelle d\'oliviers et arbres fruitiers. Préparation des trous de plantation, apport d\'amendements organiques, mise en place du paillage et du système de soutien. Conseils pour le choix des variétés adaptées à votre région.',
    disponibilite: 'Disponible en saison',
  },
  {
    id: 's8',
    titre: 'Traitement phytosanitaire',
    categorie: 'plantes',
    image: 'https://images.unsplash.com/photo-1566451887-1e28b7d8c3f8?w=600&q=80',
    prix: 200,
    unite: 'jour',
    rating: 4.6,
    nbAvis: 78,
    prestataire: 'v6',
    description: 'Traitement phytosanitaire par drone ou pulvérisateur terrestre. Lutte contre les maladies fongiques, insectes ravageurs et adventices. Produits homologués et respect des bonnes pratiques agricoles. Suivi post-traitement inclus.',
    disponibilite: 'Sur rendez-vous',
  },
  {
    id: 's9',
    titre: 'Garde et soins des animaux',
    categorie: 'animaux',
    image: 'https://images.unsplash.com/photo-1500595046743-cd271d694e30?w=600&q=80',
    prix: 80,
    unite: 'jour',
    rating: 4.7,
    nbAvis: 34,
    prestataire: 'v10',
    description: 'Service de garde, alimentation et suivi sanitaire de votre cheptel. Bovins, ovins, caprins et volailles. Personnel qualifié, respect du bien-être animal. Intervention possible en cas d\'urgence vétérinaire légère.',
    disponibilite: 'Disponible selon planning',
  },
];

// ─── PRODUITS ────────────────────────────────────────────────
const PRODUITS = [
  {
    id: 'p1',
    titre: 'Semences de blé bio',
    categorie: 'semences',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    prix: 85,
    rating: 4.7,
    nbAvis: 178,
    fournisseur: 'v7',
    stock: 50,
    disponible: true,
    description: 'Semences de blé tendre biologique certifiées AB. Variété adaptée aux conditions climatiques tunisiennes, résistante à la sécheresse et aux maladies courantes. Taux de germination > 95%. Conditionnement en sacs de 25 kg. Idéal pour l\'agriculture biologique et raisonnée.',
  },
  {
    id: 'p2',
    titre: 'Engrais organique NPK',
    categorie: 'sol',
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=600&q=80',
    prix: 45,
    rating: 4.3,
    nbAvis: 112,
    fournisseur: 'v8',
    stock: 0,
    disponible: false,
    description: 'Engrais organique complet NPK 5-3-3 à base de compost végétal et déjections animales. Améliore la structure du sol et stimule l\'activité microbienne. Action lente et durable sur toute la saison. Utilisable en agriculture biologique. Sac de 50 kg.',
  },
  {
    id: 'p3',
    titre: 'Tracteur compact 50CV',
    categorie: 'materiels',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80',
    prix: 15000,
    rating: 4.9,
    nbAvis: 245,
    fournisseur: 'v9',
    stock: 2,
    disponible: true,
    description: 'Tracteur compact 4WD 50CV moteur diesel 3 cylindres. Idéal pour les petites et moyennes exploitations. Boîte de vitesses synchronisée 12+12, prise de force indépendante, relevage hydraulique 900 kg. Cabine confortable avec climatisation. Garantie 2 ans pièces et main-d\'œuvre.',
  },
  {
    id: 'p4',
    titre: 'Aliment bétail haute énergie',
    categorie: 'aliments',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80',
    prix: 32,
    rating: 4.6,
    nbAvis: 88,
    fournisseur: 'v10',
    stock: 120,
    disponible: true,
    description: 'Aliment composé haute énergie pour bovins en production. Formule enrichie en protéines, minéraux et vitamines. Améliore les performances laitières et la croissance. Sac de 40 kg. Fabriqué selon les normes HACCP, sans OGM, sans antibiotiques de croissance.',
  },
  {
    id: 'p5',
    titre: 'Système arrosage goutte-à-goutte 1 hectare',
    categorie: 'arrosage',
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',
    prix: 450,
    rating: 4.8,
    nbAvis: 60,
    fournisseur: 'v11',
    stock: 15,
    disponible: true,
    description: 'Kit complet d\'irrigation goutte-à-goutte pour 1 hectare. Inclut : tête de réseau avec filtre à disque, tuyaux principaux PEHD, rampes de distribution, goutteurs auto-compensants, raccords et vannes. Compatible avec tous types de cultures en ligne. Installation facile, manuel inclus.',
  },
  {
    id: 'p6',
    titre: 'Plants de tomates anciennes',
    categorie: 'plantes',
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80',
    prix: 12,
    rating: 4.5,
    nbAvis: 143,
    fournisseur: 'v12',
    stock: 200,
    disponible: true,
    description: 'Plants de tomates variétés anciennes (Cœur de bœuf, Noire de Crimée, Green Zebra) produits en pépinière biologique. Plants greffés sur porte-greffe tolérant les maladies du sol. Livraison dans toute la région. Conseils de culture inclus. Prix par plant.',
  },
  {
    id: 'p7',
    titre: 'Semences de maïs hybride',
    categorie: 'semences',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    prix: 120,
    rating: 4.4,
    nbAvis: 65,
    fournisseur: 'v7',
    stock: 30,
    disponible: true,
    description: 'Semences de maïs hybride à haut rendement, adaptées au climat méditerranéen. Cycle 110 jours, tolérant la sécheresse et les fortes chaleurs. Rendement moyen 8-10 t/ha en conditions optimales. Traitement fongicide inclus. Sac de 50 000 graines (environ 1,5 ha).',
  },
  {
    id: 'p8',
    titre: 'Pulvérisateur dorsal 20L',
    categorie: 'materiels',
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&q=80',
    prix: 89,
    rating: 4.2,
    nbAvis: 47,
    fournisseur: 'v9',
    stock: 35,
    disponible: true,
    description: 'Pulvérisateur dorsal à pompe manuelle 20 litres. Cuve en polyéthylène haute résistance, rampe 4 buses réglables, lance télescopique 90 cm. Bretelles ergonomiques rembourées. Utilisable pour traitements phytosanitaires, herbicides et fertilisation foliaire. Garantie 1 an.',
  },
];